### ISSUE TITLE
Feb Milestone - Detailed plan and work distribution

### ISSUE THREAD

**Issue by Rushi-Bhatt** [Rushi-Bhatt/SE17-Team-K#8]
Things to do: 
1)Authentication - Profile creation for user, Login./Logout features (Restrict to NCSU Users)  
2)Design the views: 
a) Questionnaire to give feedback  -- Devika
b) Visualisation screen for displaying course details (description, API data and Questionnaire answers) -- Chen
c) Suggest courses - factors -- Devika
d) Profile page (My account) -- LI
e) Homepage --Rushi

3)Chat application for Forum -- Rushi
4)How to get API data from RMP and Course Description -- Li

Timeline: 
10th Feb: Complete the wireframes for each view
11th Feb: Devika and Chen - Learn Ruby on Rails properly, Rushi and Li - Try to complete task 3 and 4
12th Feb: Meet for discussing the DB schema
..
..
.. (Planning yet to come for these intermediate days)
..
..
28th Feb: Submission

**Comment by popoosl** [comment]
Designed views and models
![165259456875546449](https://cloud.githubusercontent.com/assets/21146732/22859294/c7e87854-f0a4-11e6-8dd5-d9084fd974e8.jpg)
![778473368567555847](https://cloud.githubusercontent.com/assets/21146732/22859295/c7e97a10-f0a4-11e6-85e2-a5df60799017.jpg)
![857124714804575750](https://cloud.githubusercontent.com/assets/21146732/22859296/c7e9aae4-f0a4-11e6-87b9-a643be111c37.jpg)
